; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/Arduino_JSON @ 0.1.0 ; Json parsing
    ;zinggjm/GxEPD2 @ ^1.6.0 ; EPD
    adafruit/Adafruit GFX Library @ ^1.11.11
    h2zero/NimBLE-Arduino @ ^1.4.2 ; BLE
    mathertel/OneButton @ ^2.6.1 ; Input
    arduino-libraries/NTPClient @ ^3.2.1 ; Time

; Flash and PSRAM settings for the N8R8 module
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.partitions = huge_app.csv

monitor_dtr = 1
monitor_rts = 1

build_flags = 
    -DBOARD_HAS_PSRAM=1

[env:offline_build]
build_src_filter = +<main_offline.cpp> -<main_online.cpp>

[env:online_build]
build_src_filter = +<main_online.cpp> -<main_offline.cpp>